import type { Metadata } from "next";
import { faDiscord } from '@fortawesome/free-brands-svg-icons';
import "./globals.css";
import { Header } from "./header";
import { Footer } from "./footer";

export const metadata: Metadata = {
  title: "Adeptus TEAM - New UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
